name: JS checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:

  build_lint:
    name: build_lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: |
          yarn lint:js
          yarn lint:style

      - name: Build
        run: yarn build

  integration_tests:
    name: integration_tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: test
        run: yarn test