name: E2E

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  e2e_tests:
    name: e2e_tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies of the frontend
        run: yarn

      - name: Build & Run frontend
        run: |
          yarn build
          yarn dev

      - name: Install dependencies of the e2e tests
        run: |
          cd ./e2e
          yarn
          npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30